### ISSUE TITLE
Sub-domains are not supported

### ISSUE THREAD

**Issue by nilldot** [tarwirdur/zabbix-https-checker#1]
google.com works fine, whereas a.google.com would return BAD     0
Any ideas how we can fix that ?
Thank you

**Comment by tarwirdur** [comment]
Hi.

> a.google.com would return BAD 0

Is it wrong? there is no A DNS record for `a.google.com`.
So `curl` can't connect to it and check certificate.

```
$ curl -s -o /dev/null -w "%{http_code}" -k -m 5 https://a.google.com
000
```

But it works with existing subdomains:

```
$ curl -s -o /dev/null -w "%{http_code}" -k -m 5 https://mail.google.com
301
```

P.S.
Unfortunately the script works very bad now. 
I get a lot of false events from it.

I do not recommend using it in its current form.

I wan't to rewrite it soon.

**Comment by nilldot** [comment]
Hi,
It seems ca issue actually, resulting in curl:/openssl (60) Peer's Certificate issuer is not recognised, hence failing resolution.
Need a ca-bundle update.
Thanks!
